site_name: SCLI
site_author: ozcanyarimdunya
site_description: scli
repo_name: ozcanyarimdunya/scli
repo_url: https://github.com/ozcanyarimdunya/scli

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
